/**
 * Dynamic XML Sitemap Generator for Next.js (Pages Router)
 *
 * AUTO-GENERATED by scripts/setup-sitemap.js when NEXT_PUBLIC_ENABLE_SEO=true.
 * Do NOT edit manually — run: node scripts/setup-sitemap.js
 *
 * Serves /sitemap.xml dynamically via getServerSideProps.
 * Fetches web_favicon and web_color from the API to inject into the XML
 * so the XSL stylesheet can render the correct branding in browsers.
 */

const resolveBaseUrl = (req) => {
  if (process.env.NODE_ENV === 'development' && req) {
    const protocol = req.headers['x-forwarded-proto'] || 'http';
    const host = req.headers.host || 'localhost:3000';
    return `${protocol}://${host}`;
  }
  return process.env.NEXT_PUBLIC_WEB_URL;
};

const FALLBACK_ROUTES = [
  '/', '/about-us', '/contact-us', '/faqs', '/blogs',
  '/services', '/providers', '/become-provider',
  '/privacy-policy', '/terms-and-conditions',
];

const buildFallbackSitemap = (baseUrl) => {
  const safeBaseUrl = baseUrl || process.env.NEXT_PUBLIC_WEB_URL;
  const urlEntries = FALLBACK_ROUTES.map((route) => {
    const safeRoute = route === '/' ? '' : route;
    return [
      '  <url>',
      `    <loc>${safeBaseUrl}${safeRoute}</loc>`,
      `    <lastmod>${new Date().toISOString()}</lastmod>`,
      '    <changefreq>weekly</changefreq>',
      '    <priority>0.7</priority>',
      '  </url>',
    ].join('\n');
  });
  return [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<?xml-stylesheet type="text/xsl" href="/sitemap.xsl"?>',
    '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
    ...urlEntries,
    '</urlset>',
  ].join('\n');
};

export const getServerSideProps = async ({ req, res }) => {
  const baseUrl = resolveBaseUrl(req);
  try {
    // Fetch web_favicon + web_color from API so XSL shows correct branding
    let webFavicon = '';
    let webColor = '';
    try {
      const axios = (await import('axios')).default;
      const settingsFormData = new FormData();
      settingsFormData.append('settings_type', 'web_settings');
      const settingsRes = await axios.post(
        `${process.env.NEXT_PUBLIC_API_URL}get_settings`,
        settingsFormData,
        { headers: { 'Content-Type': 'multipart/form-data' } }
      );
      const webSettings = settingsRes.data?.data?.web_settings || {};
      webFavicon = webSettings.web_favicon || '';
      webColor   = webSettings.web_color   || '';
    } catch {
      // Non-critical: XSL will fall back to defaults
    }

    const { generateSitemapXml } = await import('@/utils/sitemapBuilder');
    const sitemapXml = await generateSitemapXml({ baseUrl, webFavicon, webColor });

    res.statusCode = 200;
    res.setHeader('Content-Type', 'application/xml; charset=utf-8');
    res.setHeader('Cache-Control', 'public, s-maxage=3600, stale-while-revalidate=86400');
    res.end(sitemapXml);
    return { props: {} };
  } catch (error) {
    console.error('Failed to render sitemap.xml:', error);
    const fallbackXml = buildFallbackSitemap(baseUrl);
    res.statusCode = 200;
    res.setHeader('Content-Type', 'application/xml; charset=utf-8');
    res.setHeader('Cache-Control', 'public, s-maxage=600, stale-while-revalidate=3600');
    res.end(fallbackXml);
    return { props: { fallback: true } };
  }
};

const Sitemap = () => null;
export default Sitemap;
